### ISSUE TITLE
Cache entries are not expiring

### ISSUE THREAD

**Issue by jaytaph** [bitmaelum/bitmaelum-suite#100]
When the routing changes, we still keep the cached entries like routing and addressing There is no TTL that will automatically refresh the cache entries after a certain amount of time.

We should add an option in the server config for TTL refresh

Put this on 5 minutes?

**Comment by acalatrava** [comment]
Instead of using TTL we can ignore the cache at all during retries. So on the first attempt it will use the cache but if the delivery fails then it will move to retry queue and it will ignore the cache on the next attempts.

**Comment by jaytaph** [comment]
fixed by #101
