### ISSUE TITLE
See if we can get rid of the scary opentelemetry package

### ISSUE THREAD

**Issue by jaytaph** [bitmaelum/bitmaelum-suite#125]
Some package we use, depends on opentelemetry.. this sounds scary (even though harmless, as we don't do any telemetry whatsoever).

Just to make sure we don't get strange discussions, see if we can remove it somehow..

**Comment by jaytaph** [comment]
Unfortunately, we cannot. The go-redis/redis package uses this for adding telemetry to redis.

**Comment by acalatrava** [comment]
I think we used an old version of the reds package so we can get rid of this. Is this no longer possible?

**Comment by jaytaph** [comment]
i think we are on 8.4.4, which is the latest.. it still got the opentelemetry reference in it :(

**Comment by jaytaph** [comment]
Downgraded to v7, which does not have telemetry packages.
