### ISSUE TITLE
bm-client vault parameters are not clear

### ISSUE THREAD

**Issue by acalatrava** [bitmaelum/bitmaelum-suite#199]
**Describe the bug**
While trying to create a new vault on a specified file the parameters will induce to an error

**To Reproduce**
```
$ ./bm-client --vault test.vault vault init

Vault already exists. Use --path to create a new vault on a specific path.

$ ./bm-client --vault test.vault vault init --path .

Please enter your new vault password:
Please retype your new vault password:
error: cannot create vault:  rename . ..backup: device or resource busy
```

However this works
```
$ ./bm-client  vault init --path test.vault

Please enter your new vault password:
Please retype your new vault password:
successfully created a new vault at  test.vault
```

**Expected behavior**
Either `--path` or `--vault` should be used as parameter but not both

**Comment by jaytaph** [comment]
@acalatrava  would `--vault-path` be a more consistent name in these cases?

**Comment by acalatrava** [comment]
Yeah, I think so. The thing is that when `init` one parameter is used and when `edit` the other one. So this should be addressed.

**Comment by jaytaph** [comment]
It seems that `--path` isn't an actual parameter to begin with. Only `--vault` is used. This is changed to `--vault-path` to make it less ambigius
